### ISSUE TITLE
Make generated page's Title and meta description editable for better SEO

### ISSUE THREAD

**Issue by dimaguy** [apidoc/apidoc#1001]
# Feature request

Currently, generated api documentation uses a very lackluster title and description.

![SmartSelect_20210918-213441_Google.jpg](https://user-images.githubusercontent.com/7207103/133908198-da1ea3d5-6e33-4735-b45c-c0541f5b38a4.jpg)

Editing the template directly is prone to be reset once there is an update, so there needs to be an option to make it actually editable and permanent

**Comment by NicolasCARPi** [comment]
Hello, indeed this "Loading..." is replaced once the javascript is loaded, but I guess robots don't see that. I have made a change so that the `<title>` is immediatly the `title:` of the project's config, if no title is defined it'll be the `name:`, and fallback to `Loading...`.

Try it now on the `dev` branch and let me know if you think other things could be changed. I have also added a `meta name="description"` with the description from the config file.

**Comment by dimaguy** [comment]
Thanks for the fix! Before I close this issue, is SSR in the roadmap?

**Comment by NicolasCARPi** [comment]
> is SSR in the roadmap?

No, but it seems doable. Right now I'm focusing on making sure this new version is relatively bug free, as I've made plenty of non-trivial changes to the codebase. We can see about adding such a feature later.

**Comment by dimaguy** [comment]
Lovely to know! I'll be closing this issue now
