### ISSUE TITLE
Add options to include a folder under 'node_modules'.

### ISSUE THREAD

**Issue by dorim1209** [apidoc/apidoc#1116]
# Feature request

I want to make a document with a folder under 'node_modules'.
I knew 'node_modules' includes in 'exclude filters' as a default.

So I am using modified 'apidoc/bin/apidoc' file myself like `excludeFilters: ['apidoc.config.js']` (removed 'node_modules') and 'apidoc -i ./node_modules/exampleName/ -o ./doc' command.
Also I have to put 'apidoc.json' under 'node_modules/exampleName/'

I agree that most people wants to ignore 'node_modules' when using apidoc and I wonder if there is an option to include specific folder like the folder under 'node_modules'.

**Comment by dorim1209** [comment]
I created a PR contains this issue.

**Comment by NicolasCARPi** [comment]
See my comment on your PR ;)

**Comment by NicolasCARPi** [comment]
See my reasons for rejecting this change in the PR.

**Comment by natcohen** [comment]
@NicolasCARPi I am very interested by this...actually I can't even upgrade apidoc due to this problem.

- I had a lot of difficulties to understand the new behavior as nothing is written anywhere in the doc (from the website and the -h command line, it says default is empty: RegEx-Filter to select files / dirs that should not be parsed (many -e can be used). (default: []))
- My use case is that I use a private internal package with apidoc in it. Basically, our private package is a middleware that can return an error. This error is documented in the package but must be displayed in the doc of the service itself. Instead of rewriting the error in all our services that uses this package, we use @apiDefine in the package and reference in all our services.

From your PR comment... Why wouldn't you give more flexibility to users if the feature is ready? Even if only few users use it!

**Comment by NicolasCARPi** [comment]
Hello @natcohen 

> This should be corrected.

Done: https://github.com/apidoc/apidoc/commit/d1410c9de215f5b4f1a578568af64f2b5f7de552

> Please consider adding more flexibility to this new decision of removing node_modules by default! I truly think that not giving the choice to users is a very bad practice!

On one hand, I agree that letting users override this default exclusion filter should be possible. On the other hand, after re-reading [my comment](https://github.com/apidoc/apidoc/pull/1117#issuecomment-994873247), I agree with my past self. Having `node_modules` excluded by default seems a sensible design choice. As 99.9% of users will never need to parse code in that folder.

At the end of the day, you get what you pay for. We do not have a business relationship, we have a "I give my free time for your company" relationship, and at this time I am not enclined to make changes to fit your very particular needs.

I would suggest that you simply fork this project, make the change in `bin/apidoc` and use that fork. In alignment with [the three F's of Open Source](https://boyter.org/posts/the-three-f-s-of-open-source/).

Best,
~Nico

**Comment by NicolasCARPi** [comment]
I assumed you were maintaining something in a company context, perhaps wrongly.

> that's very sad if you contribute to open source and have this mentality!

There is nothing sad about it. It's called being an open source maintainer, sometimes it is necessary to say no.  Please have a read at this: [Saying 'No' to burnout as an open source maintainer](https://www.jeffgeerling.com/blog/2020/saying-no-burnout-open-source-maintainer).

You are free to make suggestions. I am free to ignore them.

Have a nice day!
