### ISSUE TITLE
Document change in template API in 0.50.0

### ISSUE THREAD

**Issue by codingcatgirl** [apidoc/apidoc#1151]
I'm trying to convert an [apidoc template](https://github.com/ahmed-dinar/apidoc-template) to work with the newest version of apidoc.

While trying to figure out what i need to change… i honestly just felt like giving up at some point. It would be helpful if you provided documentation about what changed. It seems to be quite a lot and it would be helpful for template authors to know – otherwise it feels like you just need to rewrite the entire template from scratch.

**Comment by codingcatgirl** [comment]
Alternatively, it would also be nice to know if there is a way to get the template from 0.50.0 back? I'm confused that the big redesign isn't even mentioned in any release notes, since imo the previous template looked much nicer.

**Comment by NicolasCARPi** [comment]
Hello,

First, a bit of context. A few months back `apidoc` wasn't actively developed. Issues and PRs were piling up since many years. The author kindly gave me write access on the repo to help with maintainance. But the codebase showed its age.

At some point, I went ahead and changed *a lot* of code to modernize the project. The dependencies were updated, the code rewritten, and the template reworked.

It was also the opportunity to make drastic changes in the codebase. For instance, merging back the `apidoc-core` code here so it's easier to work with. It was split before to provide a parsing engine to other projects. But in the end it results in bad DevX for us, and we're not even sure an active project uses it.

What I want to say is that decisions needed to be made in order to keep the project alive.

> It would be helpful if you provided documentation about what changed.

Unfortunately, this is difficult to do, as too many things changed with this release. But more importantly, `apidoc`'s maintainers don't have to care about external templates. We provide a way to use your own template, but it's not our responsability if our changes break your templates.

>  it would also be nice to know if there is a way to get the template from 0.50.0 back?

It's in the code of previous versions, do what you want with it.

>  I'm confused that the big redesign isn't even mentioned in any release notes

Well, I did put `Big CSS code overhaul and change` in Enhancements of [50.0.0](https://github.com/apidoc/apidoc/releases/tag/0.50.0). But again, there were too many changes, I listed what I could in the changelog. One big change is the way the template is generated (now with webpack), and getting rid of `requirejs` was a big piece of work.

> since imo the previous template looked much nicer.

To each his own taste ;) New CSS is much more responsive!
