### ISSUE TITLE
An error occurs when you specify a template option

### ISSUE THREAD

**Issue by gmkou** [apidoc/apidoc#1172]
# Describe the bug

I've tried to change the template with  apidoc@0.50.x. However, I found an error that the file could not be found when the template option (-t) was specified. It also occurs in the example contained in the apidoc repository.

# Steps to reproduce

```
% git clone https://github.com/apidoc/apidoc.git
% cd apidoc
% /usr/local/bin/node ./bin/apidoc -i example -o example_out -t example/template/
error: ENOENT: no such file or directory, open 'example/template/index.html'
[error] apidoc encountered an error during documentation generation!
```

# Information

- Version of apidoc: v0.50.4
- Operating system (e.g. GNU+Linux/MacOS/Windows):MacOS
- Node version: v17.4.0
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Do you have an `index.html` in `example/template` folder?

**Comment by kevinbull** [comment]
I can get the template option to work correctly if the path to the template directory is not relative to the repository root.  In my case I was able to use a template with `-t ~/projects/repo-root/docs/template`.  Otherwise, I get the same stack trace, pointing to `apidoc/lib/writer.js:94:29` as the problem.  Looks like a path resolution problem with relative paths supplied.
