### ISSUE TITLE
API Sample Request POST not sending valid JSON in body

### ISSUE THREAD

**Issue by mabashian** [apidoc/apidoc#153]
``` javascript
/**
 * @api {post} /login Login
 * @apiName Login
 * @apiGroup User

 * @apiParam {String} email Email
 * @apiParam {String} password Password

.. Success stuff here

 * @apiSampleRequest http://localhost:3000
*/
```

When I try to test the login I see the body of the request come across as something like:

`email=testemail@example.com&password=testpassword`

These look like query parameters to me.  Do I need to specify that these parameters should be sent as JSON in the body?

**Comment by haydursek** [comment]
I see this issue has been closed a long time ago. But I am still getting this issue, and I just recently started using apidocs just as of last week.

I am able to issue get requests successfully. But any request that requires the data to go in the body as json is failing because it is being written out as pointed to by the OP.

**Comment by mihairadulescu** [comment]
at least a validation that it doesn`t work ?

**Comment by ashishkhanna** [comment]
Issue is still open can you please help

**Comment by rottmann** [comment]
The sample-request plugin changed many times from different contributors, it needs to be rebuild from ground.
A contributor is needed to build this plugin, due the lack of my time i can't do it. (this i communicate here since 2014).

I changed the the project with the last update to make it easier to implement plugins. The api to integrate plugins is not finish but would be extended. So, if somebody want to build a good sample request plugin, with all the different usecases (i mark many issus with "send sample request" milestone) i would extend the plugin api to integrate such a frontend plugin.
