### ISSUE TITLE
Proposal: an alternative for output of the documentation like swagger-ui

### ISSUE THREAD

**Issue by fsbahman** [apidoc/apidoc#220]
Hi, very nice job!
I am using swagger to expose api documentation. I came across your work and now I’ve decided to bring them together, in a sense that comments are provided in code and apidoc will generate swagger friendly json schema, I will use that schema to pass to [swagger-ui] (https://github.com/swagger-api/swagger-ui) to show the documentation. It would create an alternative ui for it. I would like to know if you like it and will accept the pull request. Or any other suggestions you might have.

**Comment by robotiko** [comment]
Hi  fsbahman,
I do agree apidoc is a very nice tool, thank you guys!.
Your proposal  is quite interesting. I have been thinking the same since I found apidoc after being using swagger for quite a long time.  I think is a perfect mix because they are quite complementary. 
Swagger is great for the API test and call but not so good for documentation while apidoc is great for document, but the API testing afterwards is not as nice as swagger.
Some personal thoughts for that alternative UI: I saw some projects that user both tools, apidoc page for general doc and swagger page for testing and playing.  
The problem with that is that when learning an API, it looks like both things should be integrated in the same page, read the method doc , and then play with it before going to next one (apidoc follows this schema we are so used from school :) ).
Another suggestion/ missing detail is the api roles. In apidoc they are defined but visible, in swagger not even defined. In many cases it is relevant to hide some parts of the api to certain roles (i.e. admin routes and methods not visible to very basic users, etc) specially now that api definition is being discussed as an important design concept that can be valued as Intellectual Property for closed apis. 

Just an opinion :D

**Comment by rottmann** [comment]
@fsbahman This could be a separate project, that is why i split apidoc into the ui and [apidoc-core](https://github.com/apidoc/apidoc-core) which you can use as base to get the [json data, see apidoc-spec](https://github.com/apidoc/apidoc-spec).

apidoc itself is currently only an ui interface, that must be completely redesigned - since a long time ;-) 
I agree 100% with @robotiko, some parts are solved better in swagger, but the doc-language was the reason why i not use swagger and create apidoc. The currently existing ui was the quick result to output the json and it grow since then.

**Comment by fsbahman** [comment]
@rottmann True, I should have create this issue under apidoc-core. Let me come up with something then we will talk more. Please fill me up if you have any initial thoughts.
@robotiko Thanks for the input, I like your idea and I agree roles can bring it to the next level.

**Comment by fsbahman** [comment]
There is a first attempt to achieve this [here](https://github.com/fsbahman/apidoc-swagger). I keep working on it and will improve it. 
I would be happy to have your opinion on it. Thanks!

**Comment by rottmann** [comment]
Nice! :+1: 
Hope i get some time soon and view it in detail and i can work here on the PR and Issues :) (currently my work projects take all my time)

**Comment by rottmann** [comment]
Looks good, i will add the links to your projects in the README.md.
