### ISSUE TITLE
info: nothing to do

### ISSUE THREAD

**Issue by aajjbb** [apidoc/apidoc#247]
Hi, I've just downloaded version 0.12.2 from npm, and while trying to generate docs for a project I receive an "info: nothing to do" but nothing is created in my doc folder. 

I'm running "apidoc -i src/ -o docs/"

Thanks

**Comment by rottmann** [comment]
Hmmm not much change since previous version, can you post the `-d` debug output?

**Comment by Jermaya** [comment]
Hey, just thought I'd jump in on this because I am having the same issue. Perhaps I don't have something set up correctly but here is the debug:

$ apidoc -i FID/ -o FIDDoc/ -t mytemplate/ --debug
debug: package.json not found!
debug: read: FID\apidoc.json
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.12.3
verbose: apidoc-core version: 0.3.2
verbose: apidoc-spec version: 0.2.0
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidefineerrorstructure, ./parsers/api_define_error_structure.js
debug: load parser: apidefineheaderstructure, ./parsers/api_define_header_structure.js
debug: load parser: apidefinepermission, ./parsers/api_define_permission.js
debug: load parser: apidefinestructure, ./parsers/api_define_structure.js
debug: load parser: apidefinesuccessstructure, ./parsers/api_define_success_structure.js
debug: load parser: apigroupdescription, ./parsers/api_group_description.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apierrorstructure, ./parsers/api_error_structure.js
debug: load parser: apierrortitle, ./parsers/api_error_title.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apiheaderstructure, ./parsers/api_header_structure.js
debug: load parser: apiheadertitle, ./parsers/api_header_title.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apiparamtitle, ./parsers/api_param_title.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apistructure, ./parsers/api_structure.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apisuccessstructure, ./parsers/api_success_structure.js
debug: load parser: apisuccesstitle, ./parsers/api_success_title.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load worker: deprecatedApiErrorTitle, ./workers/deprecated_api_error_title.js
debug: load worker: deprecatedApiHeaderTitle, ./workers/deprecated_api_header_title.js
debug: load worker: deprecatedApiParamTitle, ./workers/deprecated_api_param_title.js
debug: load worker: deprecatedApiSuccessTitle, ./workers/deprecated_api_success_title.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
debug: inspect file: FID\getFlightsArrive.php
debug: size: 538
debug: inspect file: FID\getFlightsDepart.php
debug: size: 540
debug: inspect file: FID\assets\js\FlightBoardScripts.js
debug: size: 9405
debug: inspect file: FID\assets\js\FlightBoardScriptsV1-1.js
debug: size: 8526
debug: inspect file: FID\assets\js\jquery-1.11.2.min.js
debug: size: 95931
info: Nothing to do.

**Comment by Schrims** [comment]
you have to add the comments in your code - like this:
/**
     * @api {..} .. ..
     * @apiGroup XY
     * @apiDescription some text
     * @apiParam {xx} xx description
*/
and set up a package.json file

**Comment by Jermaya** [comment]
Ahh, I had them single commented with '//' just to test out a couple simple params, using the block fixed it for me. Also, I have the apidoc.json so the package.json file was not required. Thanks for the quick and helpful reply.

**Comment by Schrims** [comment]
glad that it works

**Comment by aajjbb** [comment]
It also worked for me, thanks.

**Comment by antbaobao** [comment]
thanks ,it works

**Comment by anumit02kaur** [comment]
Ah thanks a lot !!
