### ISSUE TITLE
Parameters with square brackets

### ISSUE THREAD

**Issue by stephenmuss** [apidoc/apidoc#267]
Apidoc doesn't generate the correct output when attempting to use a parameter with square brackets in its name. I currently have to work around this using dot notation. However, this then doesn't work correctly with `@apiSampleRequest`.

As an example, the query string in a request may look like `?page[offset]=0&page[limit]=10`.

Ideally I would like to use something like the following

```
@apiParam {Number} [page[offset]=0] Optional offset for paginated results.
@apiParam {Number} [page[limit]=10] Optional limit to the number of results in a paginated response.
```

Currently I am using

```
@apiParam {Object} [page="page[offset]=0&page[limit]=10"] Optional pagination query parameter.
@apiParams {Number} [page.offset=0] Optional offset for paginated results.
@apiParams {Number} [page.limit=10] Optional limit to the number of results in a paginated response.
```

Is there a workaround to get the desired effect as per the first example or is this an issue that needs to be addressed?

**Comment by rottmann** [comment]
The sample request library is really rudimentary and will be replaced.

**Comment by stephenmuss** [comment]
Is it possible in any way to represent parameters with square brackets? How can I do something like `@apiParam {Number} page[offset] Offset for paginated results`?

**Comment by zxqfox** [comment]
> @apiParam {Object} [page="page[offset]=0&page[limit]=10"]

Standard is:
```
@param {{offset: Number, limit: Number}} page description
```

Why not to use something like that for `@apiParam`?

**Comment by zxqfox** [comment]
@stephenmuss Square brackets in names is used as optionality mark (as well as `?`-prefix).

It's easy to parse strings like `[page[limit]=10]` but it's non-standard thing, just why?

**Comment by stephenmuss** [comment]
@zxqfox I'm working to a specification and nested query parameters use square brackets.

Therefore query strings such as `page[offset]=100&page[limit]=50` are necessary. This is not uncommon in several APIs. See [Stripe](https://stripe.com/docs/api/curl) as an example.

**Comment by zxqfox** [comment]
@stephenmuss Yeah, sure. But when we talking about jsdoc-like things it looks at least strange.

**Comment by rottmann** [comment]
You have the usecase for brackets in URL-Queries `page[offset]=100&page[limit]=50`, the next one need a JSON-Object
```
{
  "page": {
    "offset": 100,
    "limit": 50
  }
}
```

the next need xml
```
<page>
  <offset>100</offset>
  <limit">50</limit>
</page>
```

or with attributes
```
<page offset="100" limit="50"/>
```

or a csv format
```
offset.limit
100,50
```

or as text format - yes, i really saw this "api" from a small Bank ;-)
```
offset=100\n
limit=50\n
```

That is not the problem of apiDocs apiParam spelling.
In apidoc you write the apiParams in an uniform way, so that everybody can read and write the **source** without knowing what kind of "output"-format will be used.

That is why i write that the output-library (sending sample requests) is really rudimentary, because somebody write it to solve his specific problem (send a simple json request).

The library will be replaced and currently i think a configuration var or a new annotation `@apiFromat` is necessary to support the different output formats.
e.g. `@apiFormat JSON`, `@apiFormat URL-Query`,  `@apiFormat XML`...

Good that we can discuss here the ideas and fix this problem. :+1:

**Comment by dhotson** [comment]
Hey guys, good discussion so far. I have a few thoughts on this. :)


I think that trying to convert between input param name formats (e.g. `foo.bar` to `foo[bar]`) seems complicated and unnecessary.

I don't think apidoc needs to be too smart about parsing these kinds of parameter names. In my specific case, the API param names include square brackets—but it's not something I'd expect apidoc to attempt to parse.

Ultimately, my expectation is that the param name in apidoc (and the generated documentation) should match what the user will use when they call the API. The current limitation on parameter names makes it difficult to make everything match.

**Comment by stephenmuss** [comment]
@dhotson agree completely with what you say.

**Comment by dhotson** [comment]
Hey @rottmann, sorry to be a pain, I just wanted to check if there are any updates on this.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
