### ISSUE TITLE
Included sampleUrl in apidoc.json - getting "Error 0:" in the Response form field

### ISSUE THREAD

**Issue by jhaaaa** [apidoc/apidoc#293]
Newbie troubleshooting this error - but not sure of where to start. Is it something in my config file, .js file, or my authorization values?

Should this just work out of the gate when I click Send in the generated API doc, or is further setup required?

I've googled to my heart's content and can't find any info.

Thank you!

J-Ha

**Comment by jhaaaa** [comment]
Of course, seeing my content would help. the "xxxxxx" is an actual value in my files.

Here is my apidoc.json:
{
    "name": "Example API",
    "version": "0.1.0",
    "description": "Example API",
    "title": "Example API",
    "url": "https://jha-test.xxxxxx.com",
    "sampleUrl": "https://jha-test.xxxxxx.com",
    "template": {
        "withCompare": true,
        "withGenerator": true
    }
}

Here is my example.js:

/**
 * @api {get} /api/v3/users.xml Get users
 * @apiVersion 0.1.0
 * @apiName Get Users
 * @apiGroup Users
 * 
 * @apiHeader {String} Authorization Your API key and password blah blah blah
 *
 * @apiParam {Number} from_id Set this value to...
 * @apiParam {Number} page Set to the page number...
 * @apiParam {Number} status Set to the status...
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     <users type="array">
 *        <user>
 *           <distinguished-name nil="true"></distinguished-name>
 *           <email>user@company.com</email>
 *           <external-id nil="true"></external-id>
 *           <firstname>Alejandro</firstname>
 *           <id>123456</id>
 *           <lastname>Whitman</lastname>
 *           <member-of nil="true"></member-of>
 *           <status>4</status>
 *           <username>alewhitman</username>
 *        </user>
 *        <user>
 *           <distinguished-name nil="true"></distinguished-name>
 *           <email>user@org.com</email>
 *           <external-id nil="true"></external-id>
 *           <firstname>Aiko</firstname>
 *           <id>654321</id>
 *           <lastname>Chavez</lastname>
 *           <member-of nil="true"></member-of>
 *           <status>1</status>
 *           <username></username>
 *        </user>
 *     </users>
 *
 * @apiErrorExample
 *     HTTP/1.1 401 Unauthorized
 *     <error>
 *        <title>Unauthorized Access</title>
 *        <message>Your IP is not allowed to use this API...</message>
 *     </error>
 */

/**
 * @api {get} /api/v1/roles.xml Get all roles
 * @apiVersion 0.1.0
 * @apiName Get Roles
 * @apiGroup Roles
 * 
 * @apiHeader {String} Authorization Your API key and password blah blah blah
 *
 * @apiSuccess {String} id Unique ID assigned to the role
 * @apiSuccess {String} name Name of the role
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     <roles type="array">
 *        <role>
 *           <id>12345</id>
 *           <name>Employee</name>
 *        </role>
 *        <role>
 *           <id>54321</id>
 *           <name>Manager</name>
 *        </role>
 *     </roles>
 */

**Comment by natematykiewicz** [comment]
Are you hosting your docs on a different domain than your API (or trying to test them out on your local machine)? If you are, you're probably running into a Cross Site Scripting error.

If you open up the development console in Chrome, you will probably see:
> No 'Access-Control-Allow-Origin' header is present on the requested resource
And if you do, you might even see this before it:
> OPTIONS https://jha-test.xxxxxx.com/api/v3/users.xml?{} 404 (Not Found)

If this is the case, this means your browser is trying to keep you safe from Cross Site Script attacks.

The OPTIONS request is your browser trying to determine if it's safe to do the GET request even though it's an AJAX call to a different domain. If you host your docs on the same domain as your API, the docs will "just work". The browser won't attempt to do an OPTIONS request to that endpoint because it's clearly safe to do a GET since it's all the same domain.

If hosting the docs on the same domain as your API isn't an option for you, you can also set up your API to be CORS friendly.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by jhaaaa** [comment]
Hi @natematykiewicz -- thank you for your thoughtful and thorough reply! Makes complete sense - I am indeed just trying to make the call from my laptop. I'm on it -- can't wait to get this up and running. apiDoc rocks! Thank you again!
