### ISSUE TITLE
Please create a new npm since the formatting of the test-response is broken.

### ISSUE THREAD

**Issue by alqu** [apidoc/apidoc#405]
Hi,

in the git-repo the response formatting- and sending works really good. Just update the npm package to also transport those enhancements to eg. gulp-apidoc.

Thanks in advance

Michael

**Comment by jorgerdz** [comment]
+1

**Comment by sbowler** [comment]
It sounds like you are referring to gulp-apidoc, which is a different repo. I did see that @rottmann  stated he would gladly link to it more officially in https://github.com/apidoc/apidoc/issues/32 . It looks like all of the changes that were lacking then have been addressed a long time ago. I think that issue is still valid and it would be nice to have a more official gulp wrapper since a lot of people use gulp.

**Comment by rottmann** [comment]
Yep, gulp-apidoc is not my repo.

**Comment by alqu** [comment]
OK, yes, I see.

Hm. Sorry for bugging you.
