### ISSUE TITLE
Is 'type' a keyword in @apiParam?

### ISSUE THREAD

**Issue by miparnisari** [apidoc/apidoc#491]
This comment 

`@apiParam [String] type the type of the account`

Produces

![bug](https://cloud.githubusercontent.com/assets/5374887/16210947/1930ec04-3715-11e6-80dd-8a722d6267cc.png)

**Comment by jmkarin** [comment]
The problem is that String should be in curly braces. Square brackets like that indicate an optional parameter name. Thus, by using them you're saying that the name of your optional parameter is String and everything following that name is the description - exactly what was produced in your output.

Do this instead:

@apiParam {String} type the type of the account
 
and you will get a required (no optional notation) parameter of type String with name type.

**Comment by miparnisari** [comment]
Ah okay, thanks!
