### ISSUE TITLE
Name of my method

### ISSUE THREAD

**Issue by martinsdesa** [apidoc/apidoc#497]
Can i change the name of my methods?
I try this: 
`/**     
     * @api {get} /cores/delete/:id  
     * @apiGroup Cores
     * @apiName delete   
     * @apiParam {Number} id
     */`

`       /**
     * @api {get} /cores/details
     * @apiGroup Cores
     * @apiName details
     * @apiParam {Number} id //passado como query string
     */`

In this way, all methods are named "Cores"

![api_doc](https://cloud.githubusercontent.com/assets/5799507/16383254/c189ef5a-3c5a-11e6-9133-10505288c1c2.png)

**Comment by jmkarin** [comment]
Any content you put after the call itself will be used as the display name of the endpoint. Right now everything is showing up as Cores because that's the group name and you haven't defined any endpoint names. If you use the following:

``/** * @api {get} /cores/delete/:id Delete Core
* @apiGroup Cores 
* @apiName delete 
* @apiParam {Number} id */``

The heading will show up as "Cores - Delete Core"

**Comment by jofee** [comment]
@jmkarin Where's the @apiName delete ?

**Comment by rottmann** [comment]
The apiName is only a name, important is first line `@api {get} /cores/delete/:id Delete Core` `Delete Core` will be the title.
