### ISSUE TITLE
@apiVersion in @apiDefine produces error

### ISSUE THREAD

**Issue by Szellem** [apidoc/apidoc#522]
Hi,

I'd like to have the same version in all endpoints in my documentation. To achieve this the following code was used:
```
/**
 * @apiDefine ApiVersion
 * @apiVersion 2.0.0
 */
  /**
   * @api {get} /user/:id
   * @apiUse ApiVersion
   */
```
This gives the following error:
```
error: Referenced definition has no matching or a higher version. Check version number in referenced define block. 
{ File: 'src/main/java/apitest/ApiTest.java',
  Block: 2,
  Element: '@apiUse',
  Groupname: 'ApiVersion',
  Version: '0.0.0',
  'Defined versions': [ '2.0.0' ],
  Definition: '@apiUse group',
  Example: '@apiDefine MyValidGroup Some title\n@apiUse MyValidGroup' }
```
When I change the code to
```
/**
 * @apiDefine ApiVersion @apiVersion 2.0.0
 */
```
the documentation is generated but version information is not added to the endpoint (it is 0.0.0).

Version is 0.16.1 with Java.

Am I doing something wrong? Is there any other way to achieve the original goal (keeping the versions of all endpoints at one place)?

Thanks!

**Comment by PunchyRascal** [comment]
As I understand the error, you can't remove version from a block, because each block needs to have a version to know, what version of another block to include (in case you want to version your blocks, which makes sense). I tried this as well, but I suppose it is a limitation that you have to indicate the version everywhere manually.  I could be wrong.

**Comment by rottmann** [comment]
@PunchyRascal  correct.

A method normally has always a version, or no version for all.
With a global version, lazy developer forget to set a local version and that produces a wrong doc.
