### ISSUE TITLE
Problem with Versioning

### ISSUE THREAD

**Issue by ezdata** [apidoc/apidoc#540]
I'm able to generate documents with a problem. However, when I increment the version on my documents, while I do get the "Compare all with predecessor" option, when I select it nothing happens. 

I created the _apidoc.js file and put it into almost every directory I can think of: root directory of my project, the subdirectory of the file being parsed, a directory higher. The result is the same. It's as if _apidoc.js is not being read.

So...answers to obvious questions.
1. I've incremented the API version number in apidoc.json.
2. The document block with my PHP file for the specific function has been incremented and is the same number as in apidoc.json
3. _apidoc.js has the previous version's docblock.
4. This project is in Laravel. Here's the command I'm using to run the documentation: 
`apidoc -i /Applications/MAMP/htdocs/myproject/app/Http/Controllers -o /Applications/MAMP/htdocs/myproject/public/docs/`

What am I overlooking? Any help would be appreciated.

Jeff

**Comment by rottmann** [comment]
the _apidocj.js is in the Controllers dir?

**Comment by cerino-ligutom** [comment]
This issue might be really old but might help someone who stumbles into this as I did today. I tried everything that @ezdata said but no luck as well. 

In my case, I was using the `-f` flag (file filters) since I'm working with TypeScript files. Full command is `apidoc -f \".*routes.ts$\" -i ./src/routes/ -o ./apidoc/`. When I removed that, it started working. 

Had me wondering why this worked so I had to test if the regex file filter, when set, bypasses the suggested `_apidoc.js` as per documentation. Renamed `_apidoc.js` to `_apidoc.routes.ts` and boom, worked.

This should be documented imo. Where setting `-f` bypasses the suggested `_apidoc.js` if your regex filter doesn't check `.js` extensions.
