### ISSUE TITLE
@apiDeprecated not working?

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#694]
I have this:
/**
 * @api {get} /notifications/:request_id/:notification_type Request Notifications Resend Deprecated
 * @apiName Request Notifications Resend
 * @apiGroup Resend
 * @apiVersion 1.0.0
 *
 * @apiDescription Get the status of notifications for a request job - **This method is deprecated**
 *
 * @apiDeprecated
 * 
 * @apiHeader {String} X-BC-ONCE-API-KEY: {api_key}
 * ....

but the @apiDeprecation isn't doing anything -- am I not using it correctly? (there is no alternative method to point to here)

**Comment by ehallander9591** [comment]
I will say this. First in case case is important we use @apiDeprecated. Second we make it the first item in the comments field, and it does something for us.

'''js
/**
 * @apiDeprecated We no longer support this
 * @api {get} /something Something to get
 * @apiName MyName
```

**Comment by bato3** [comment]
`@apideprecated` require message

**Comment by jbylsma** [comment]
The [docs](http://apidocjs.com/#param-api-deprecated) specify that `@apiDeprecated` does not require a message. However, I was having an issue with parameters not appearing in the final output, and it turned out that parameters after a valueless parameters (`@apiDeprecated` and `@apiPrivate`) would parsed as the value for those valueless parameters. I've created a [pull request](https://github.com/apidoc/apidoc-core/pull/71) for the regular expression parser change. Maybe that's the issue here?

**Comment by NicolasCARPi** [comment]
PR merged!

**Comment by MoonChaserChen** [comment]
I have encountered the same question:
I have an api of version 0.1.1, but I want to deprecated this api from 0.1.2, I failed. And if i just add `@apiDeprecated` on version 0.1.1(there will not be an version of 0.1.2 of this api), it works for me.
