### ISSUE TITLE
Define import

### ISSUE THREAD

**Issue by boxsnake** [apidoc/apidoc#712]
I am wondering if there is an way to import `@apiDefine` from another file.

In my situation, I use an unified error code list for my apis. Thus, I do not want the error code be messed up. I want to define all available error codes with `@apiDefine` in a separate file and import into the I am using `@apiUse` annotation.

Thanks.

**Comment by Rastalamm** [comment]
+1 for this. 

I have generic authentication and server responses that I would like to share across all my API routes and not have to copy/paste the @apiDefine in every route file I have

**Comment by Rastalamm** [comment]
@boxsnake - Turns out this is default behavior. 

File structure:
api 
  -- docTemplates
    -- errorTemplates.js
  -- routes
    -- get.js

In the api/docTemplates/errorTemplates.js file I have the below error definition

```
/**
  @apiDefine ServerError
  @apiError ServerError There was a problem processing your request
  @apiErrorExample ServerError
    HTTP/1.1 500 Not Found
    "Internal Server Error"
*/

```
In api/routes/get.js I have the below error usage declarataion 

`@apiUse ServerError
`

In the documentation output, it outputs the server error
<img width="1041" alt="screen shot 2018-04-12 at 9 39 48 pm" src="https://user-images.githubusercontent.com/9030131/38712508-3351af40-3e9a-11e8-90a3-0d0253a84ecb.png">

**Comment by boxsnake** [comment]
@boxsnake The default behavior is: when generating apidoc, this tool exports all comments into a common space based on your input path(s), no matter where the comment is located.
