### ISSUE TITLE
@api {post}  is being sent as OPTIONS

### ISSUE THREAD

**Issue by ali-abbas-10p** [apidoc/apidoc#731]
Below is comment code of API doc.
If I use apidoc to send a request, it is being sent as OPTIONS instead of POST.
My sample URL is http://localhost:4000/api/v1.

Can you please which mistake I am doing?

/**
 * @api       {POST} /profile Post User profile
 * @apiName   PostProfile
 * @apiGroup  Profile
 * @apiHeader {String}  Authorization  Cognito user token
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
 *        "statusCode": 200,
 *        "message": "success"
 *     }
 * @apiError User User already exist / User role is invalid
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 400 Bad-Request
 *     {
 *        "statusCode": 400,
 *        "message": "User role is invalid"
 *     }
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 409 Conflict
 *     {
 *        "statusCode": 409,
 *        "message": "User already exist"
 *     }
 */

**Comment by unsol** [comment]
I encountered this exact issue. This issue is related to CORS (Cross-Origin Resource Sharing), and not apiDoc.

To resolve this, make sure that the sample request URL matches the URL you see in your address bar.

For example, you may have entered http://127.0.0.1:4000/api/v1 in your browser, which will pull up the apiDoc page just fine, but your sample request URL is trying to POST to http://localhost:4000/api/v1, which falls under that cross-origin restriction.

**Comment by unsol** [comment]
I encountered this exact issue. This issue is related to CORS (Cross-Origin Resource Sharing), and not apiDoc.

To resolve this, make sure that the sample request URL matches the URL you see in your address bar.

For example, you may have entered http://127.0.0.1:4000/api/v1 in your browser, which will pull up the apiDoc page just fine, but your sample request URL is  POST to http://localhost:4000/api/v1, which falls under that cross-origin restriction.

**Comment by ali-abbas-10p** [comment]
Thanks, @unsol . It solved my problem.
