### ISSUE TITLE
Ability to tag apis

### ISSUE THREAD

**Issue by neelbhanushali** [apidoc/apidoc#832]
# Feature request

An ability to tag apis to identify in which app they are used is awaited and will be very appreciated by users.

**Comment by NicolasCARPi** [comment]
So @apiTag?

**Comment by neelbhanushali** [comment]
@apiTags since there is a possibility there can be more than one

**Comment by neelbhanushali** [comment]
@NicolasCARPi can you tell me how does `bin/apidoc` convert all the apidoc comment blocks to `api_data.js` and `api_data.json`?

I'm willing to raise a PR for this

**Comment by omargho** [comment]
@neelbhanushali apidoc use [apidoc-core](https://github.com/apidoc/apidoc-core) in order to parse all the comment blocks and then it return an object that contain all the parsed information as you can see here https://github.com/apidoc/apidoc/blob/8684aec24548291064e62c1f5deca062c15a914c/lib/index.js#L122 
`apidoc` in the snippet above is an instance of apidoc-core lib
https://github.com/apidoc/apidoc/blob/8684aec24548291064e62c1f5deca062c15a914c/lib/index.js#L2
`api` object then is used to create the template 
https://github.com/apidoc/apidoc/blob/8684aec24548291064e62c1f5deca062c15a914c/lib/index.js#L132

**Comment by neelbhanushali** [comment]
@omargho I'll have to raise a PR on [apidoc-core](https://github.com/apidoc/apidoc-core) repo to give support for `@apiTags` right?

**Comment by rottmann** [comment]
Can you give me some example for the usecase of apiTag. Normally one api-doc is a documentation for one api.
I am always very careful with the inclusion of new methods.

If it must not be included into the core, it is possible to add it as a plugin. (basic example https://github.com/apidoc/apidoc-plugin-test)

Ref: apidoc/apidoc-core#94

**Comment by neelbhanushali** [comment]
@rottmann 

Lets say documentation was created using actors as groups.
But there is a requirement to show in which app(s) a particular API is to be used, then this comes into use.

**Comment by NicolasCARPi** [comment]
> I am always very careful with the inclusion of new methods.

@rottmann So what do you think of https://github.com/apidoc/apidoc-core/pull/94 ?

**Comment by rottmann** [comment]
@NicolasCARPi let it currently open, iam still not sure about it. 
Finish currently a project and will (hopefully 🙏) have in two weeks enough time to test it with an example.

**Comment by NicolasCARPi** [comment]
This won't be implemented.
