### ISSUE TITLE
Duplicate element name ??

### ISSUE THREAD

**Issue by lee149205** [apidoc/apidoc#876]
<img width="1404" alt="Screen Shot 2020-05-05 at 8 33 32 AM" src="https://user-images.githubusercontent.com/11714006/81028314-043ed580-8eab-11ea-8ff0-a19b4449ce08.png">

In document, i have many input use same name 
How to fix it ?
Thanks

**Comment by rafaelgssa** [comment]
Can you share your configuration so this issue can be reproduced?

**Comment by lee149205** [comment]
apidoc.json
`{
    "name": "ABC Core",
    "version": "1.0.0",
    "description": "",
    "title": "ABC API Documents Core",
    "url" : "http://api.abc",
    "sampleUrl": "http://api.abc",
    "template": {
        "withGenerator": false
    }
}
`

auth.js

/**
 * @api {post} /login Login
 * @apiGroup Auth
 *
 *
 * @apiParam {Number} client_id
 * @apiParam {String} client_secret
 * @apiParam {String} username
 * @apiParam {String} password
 *
 * @apiSuccessExample Success-Response:
 {
        "success": true,
        "data":
            {
                "token_type": "Bearer",
                "expires_in": 86400,
                "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6I....."
            }
    }
 */

/**
 * @api {post} /register Register
 * @apiGroup Auth
 *
 * @apiParam {Number} client_id
 * @apiParam {String} client_secret
 * @apiParam {String} name
 * @apiParam {String} [email]
 * @apiParam {String} phone
 * @apiParam {String} password
 * @apiParam {String} password_confirmation
 * @apiParam {Url} [website]
 * @apiParam {String} [tax_code]
 *
 * @apiSuccessExample Success-Response:
 {
        "success": true,
        "data":
            {
                "id": "d24859e8-ae41-4e1e-9042-7ec0c7deb292",
                "name": "chinh",
                "email": "chinh@yahoo.com",
                "short_id": null,
                "type": "org_admin",
            }
    }
 */

**Comment by PenguinScola** [comment]
This occurs on 0.23.0 too. Please advice how can I fix it.

Here is my config.

{
  "name": "My API Reference",
  "version": "1.0.0",
  "description": "The official APIs documentation",
  "title": "My API reference index",
  "url": "http://my-url.com/api",
  "sampleUrl": "http://my-url.com/api"
}

**Comment by Drozeral** [comment]
Hi,

Same problem here. This happens when you have several APIs that use parameters with same names.

I think that the default template in `index.html` is wrong at line 299 : `id="sample-request-param-field-{{field}}"` should be replaced by something like `id="{{../id}}-sample-request-param-field-{{field}}"`. This way the HTML identifier would be unique for each parameter name and for each API.

The same problem occurs for `id="sample-request-body-json"` at line 289 : it should be replaced by something like `id="{{../id}}-sample-request-body-json"`.

Hopefully the problem can be fixed, because we can't click on the labels linked to inputs because of this bug! Thank you!

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
