### ISSUE TITLE
filename leak/include absolute path to file

### ISSUE THREAD

**Issue by gemal** [apidoc/apidoc#886]
using version 0.22.1 to generate the apidoc:

my api_data.json contains the following data:

```
"version": "0.0.0",
"filename": "/xxx/xxx/xxxx/XxxxController.php",
"groupTitle": "Xxxx",
```

why does it include the full path of my file?

the information is not used in the interface and I think it's a leak of unnecessary information

**Comment by NicolasCARPi** [comment]
I have relative paths in mine:

![2020-06-05-055454_433x62_scrot](https://user-images.githubusercontent.com/3043706/83835469-2073a380-a6f1-11ea-8d7e-7283cadebdd4.png)

It turns out that if you use a full path for the `-i` param, you'll get full path in the `api_data.json`.

So the solution here is to use a relative path ;)

**Comment by gemal** [comment]
isn't that also leak of unnecessary information?
`src/controllers/ApiController.php`

**Comment by gemal** [comment]
what is the filename used for? I don't see it anywhere in the UI
Perhaps it could just be removed?

**Comment by rottmann** [comment]
@gemal It is not used in the current public template. I used it in internal documentations to link to files and sourcecode.

But we can think about to add an option / filter to remove or add such data.

**Comment by NicolasCARPi** [comment]
I have addressed this issue.
