### ISSUE TITLE
Documentation about `sampleUrl` parameter

### ISSUE THREAD

**Issue by sw360cab** [apidoc/apidoc#929]
# Describe the bug

`apidoc` documentation says:

> sampleUrl If set, a form to test an api method (send a request) will be visible. See @apiSampleRequest for more details.

# Steps to reproduce

whether key is not present, or key is empty the sample form is always present in each api entry, using `url` as reference url.
Is there a way to globally hide this form, instead of disabling it for each api entry?

# Information

- Version of apidoc: 0.26

**Comment by sw360cab** [comment]
> Without sampleUrl only methods with @apiSampleRequest will have a form

This is either not true

**Comment by NicolasCARPi** [comment]
I can confirm. Without the key the url is null/user. Might have been a bug introduced by https://github.com/apidoc/apidoc/pull/915

ping @thealphadollar

**Comment by thealphadollar** [comment]
Hey @sw360cab ! This was the desired behavior implemented in #915 by me. I had done the same since having a default sample URL (i.e. the URL where the docs are hosted) helps in quick development and testing. Personally, we at @zealth-ai had the use-case of allowing developers to quickly produce code and test without editing `sampleUrl` on their local systems.

> the sample form is always present in each api entry

If I understand correctly, what you desire is that the sample request form is disabled when`sampleUrl` is empty.

I think we can go about this in two ways - either we update the documentation to reflect that a default URL will be there or we add a new variable (let's say `disableSampleRequestForm`) which is false by default and should be set to true if the user doesn't want sample request form to be present.

Please let me know your views and I'll make the fix according to what is comfortable to all of us.

**Comment by sw360cab** [comment]
@thealphadollar IMHO the doc should be consistent (especially for APIDOC ! 😅)

I think that the possibility to have a different granularity for sample forms should be kept. I may want to disable form for a single api or for the whole documentation.
As far as I am concerned not having the "sampleUrl" specified should be the right path to follow to achieve that. But if the fallbak to url is a must, I don't see other ways other than adding one more parameter to global config.

Consider also `fallbackSampleUrlToUrl` as another opportunity of global parameter which may lead to the same final result.

**Comment by thealphadollar** [comment]
The idea to add a fallback URL seems exciting. I think that would serve both the purpose - a boolean to activate default form with the site URL if not sampleUrl is specified. Once @NicolasCARPi confirms the same, I'll look into how we can implement the same.

**Comment by NicolasCARPi** [comment]
Yes, a config switch sounds good!

**Comment by solsticesurfer** [comment]
I second the request to have a global switch to disable the form. They're a great idea but we don't use them (we have other tools that we use) and it just introduces noise. I would suggest not relying on the **sampleUrl** configuration property since that might break things. Instead, I would suggest something along the lines of **useSampleForms** with a default value of true.

**Comment by thealphadollar** [comment]
I've raised a fix for the same - https://github.com/apidoc/apidoc/pull/930
