### ISSUE TITLE
Handlebars.compile error since version 0.28.0

### ISSUE THREAD

**Issue by alex-michaud** [apidoc/apidoc#967]
# Describe the bug
Cannot open the doc if compiled with apidoc 0.28.0

# Steps to reproduce

1 - compile doc with apidoc 0.28.0
2 - try to open the doc with firefox or chrome, in the browser devtool you will see the error : "TypeError: Handlebars.compile is not a function"

# Information

- Version of apidoc: 0.28.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux
- Browser (e.g. firefox, chrome): Firefox and Chrome

**Comment by a-tonchev** [comment]
Same here

**Comment by NicolasCARPi** [comment]
@0skSG could you have a look? Probably linked to your PR, no?

**Comment by kipaut** [comment]
I have the same problem
Rolled back to version 0.27.0

Version of apidoc: 0.28.0
Operating system : Linux
Browser: Chrome Version 90.0.4430.85

**Comment by 0skSG** [comment]
In fact it could be ralated. I cannot discard that option.
What I did in my [last PR ](https://github.com/apidoc/apidoc/pull/962)was to update the hardcoded minified file inside the vendor folder, downloading it from [here](https://handlebarsjs.com/installation/#downloading-handlebars).
Please provide any feedback or suggestion, I honestly though PR's checks and reviews were covering the needed scenarios.

**Comment by OliverwengFiltered** [comment]
same issue here, had to downgrade to the previous version.

**Comment by 0skSG** [comment]
Hello, I've been investigating a bit more on that.
I managed to fix this issue in my local machine replacing the handlebars.min file that right now with v0.28.0 is installing in my node_modules folders, by the one that I'm adding in this PR https://github.com/apidoc/apidoc/pull/969.
Should be fine if someone else can double check that, downloading from [here](https://handlebarsjs.com/installation/#downloading-handlebars) the version that contains the compiler + the runtime.
Thank you.

**Comment by NicolasCARPi** [comment]
Fixed in 0.28.1.

**Comment by seyfer** [comment]
Seems like this issue PR caused another issue. Now I am getting
```
"Missing helper: \"if_neq\""
```
Should be replaced to `unless` everywhere.

**Comment by prashant93** [comment]
not fixed in 0.28.1

**Comment by prashant93** [comment]
![image](https://user-images.githubusercontent.com/4151470/126316624-40a8bb4f-2fd8-4b04-9882-86eca6463d32.png)

![image](https://user-images.githubusercontent.com/4151470/126316702-5c28f581-b95f-432a-8639-43b2dcea4756.png)

**Comment by NicolasCARPi** [comment]
@prashant93 this issue is with your CSP policy, no? Nothing to do with the lib.

**Comment by prashant93** [comment]
Thanks @NicolasCARPi

**Comment by seyfer** [comment]
why not to add handlebars ^4.7.7 to package json as a dependency?

**Comment by NicolasCARPi** [comment]
> @NicolasCARPi why not add handlebars ^4.7.7 to package JSON as a dependency?

What do you mean? It's there already!

And yes it's loading it from the `template/vendor` directory, but it's 4.7.7, at least in `master` branch.

This is something I want to fix: load stuff from node_modules with a webpack step. But I did not write this software, I'm just dedicating some time to it because it was almost abandoned at some point, fortunately the owner gave me some access to try and help. So there is a lot of technical debt that accumulated and it requires a significant amount of work to bring it to today's web standards.

As for the missing helper thing, a new patch should come out, because the current latest version on npm has this bug, but not the version from master.

**Comment by seyfer** [comment]
@NicolasCARPi ahh, thank yopu very much, I was about to try `master` today instead of latest version. Had a feeling that maybe fixes were not tagged yet in a new version. Or will wait for `0.28.2` with fixes.

**Comment by NicolasCARPi** [comment]
>  bring more maintainers on board if you feel like you need help. :)

@seyfer, well this is exactly why I proposed my help to @rottmann. I saw he needed help with issue triage, merging PR and fixing bugs. But you know, finding someone that will actually help with the project is easiest said than done. Most people are happy to propose their help but when it comes to actually doing something it ends up with "sorry I didn't have time but I'll have some next week". Everyone can make PRs and comment on issues.

Some of the big issues with this project:

- it doesn't generate money for its creator -> hence the lost in interest, one has to feed his family and focus on projects that do
- the codebase has accumulated a lot of debt over time and there was some dubious design choices (like putting the parser as another repo, makes things difficult ; I mean there was a good reason at the time, but it turns out it's not so great).
- I'm not familiar enough with the codebase to rewrite a large part of it and make it "great again"
- because of its popularity, there are a lot of users with issues to deal with, and this can lead to the "open source maintainer burnout", with a never ending stream of bug reports and feature requests, and only a very small percentage of PR actually fixing bugs and not introducing more code to maintain/fix.

Some of the big advantages of this project:

- @rottmann is still present and publishing things on npm when I tag new releases
- the popularity of this project makes it more likely to get good PRs
- it kind does what we want it to do, more or less :laughing: 

![giphy](https://user-images.githubusercontent.com/3043706/128010928-2d642ec1-d3c6-4b70-b0b5-a7e90d176b1f.gif)

Anyway, I'm here to fix the leaks and do basic maintainance. Maybe at some point I'll give this project a good whip, but with @rottmann we discussed about starting from scratch, which could be the death or rebirth of this project, hard to say, sometimes planning a complete rewrite is a bad idea, sometimes it is good. I'm all for a rewrite, but one has to consider the scope of such a project, it's far from being trivial. So in the end, maybe fixing what exists might be better...

Maybe I'll start by deprecating apidoc-core and importing the parser in this repo... @rottmann what do you think about such a change? It's never too late to revert a bad decision!
